package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/wtgoku-create/popiartcli/internal/agentpaths"
	"github.com/wtgoku-create/popiartcli/internal/config"
	"github.com/wtgoku-create/popiartcli/internal/output"
)

func resolveNativeAgentPaths(agent string) (agentpaths.Paths, error) {
	return agentpaths.Resolve(agent)
}

func writeNativeAgentMCPConfigFile(agent string, cfg config.Config) (bootstrapGeneratedFile, error) {
	paths, err := resolveNativeAgentPaths(agent)
	if err != nil {
		return bootstrapGeneratedFile{}, err
	}

	if err := os.MkdirAll(filepath.Dir(paths.MCPConfigPath), 0o700); err != nil {
		return bootstrapGeneratedFile{}, output.NewError("CLI_ERROR", "创建 agent MCP 配置目录失败", map[string]any{
			"path":    filepath.Dir(paths.MCPConfigPath),
			"details": err.Error(),
		})
	}

	switch paths.Agent {
	case "codex":
		if err := upsertCodexMCPConfig(paths.MCPConfigPath, cfg); err != nil {
			return bootstrapGeneratedFile{}, err
		}
	default:
		if err := upsertJSONMCPConfig(paths.MCPConfigPath, cfg); err != nil {
			return bootstrapGeneratedFile{}, err
		}
	}

	return bootstrapGeneratedFile{
		Kind: "agent-mcp-native",
		Name: agent + " native MCP",
		Path: paths.MCPConfigPath,
	}, nil
}

func writeNativeAgentSkillWrapper(agent string) (bootstrapGeneratedFile, error) {
	paths, err := resolveNativeAgentPaths(agent)
	if err != nil {
		return bootstrapGeneratedFile{}, err
	}

	dir := filepath.Join(paths.SkillDir, popiartMCPServerID)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return bootstrapGeneratedFile{}, output.NewError("CLI_ERROR", "创建 agent skill 目录失败", map[string]any{
			"path":    dir,
			"details": err.Error(),
		})
	}

	path := filepath.Join(dir, "SKILL.md")
	if err := os.WriteFile(path, []byte(strings.Join(buildAgentSkillWrapperLines(), "\n")), 0o600); err != nil {
		return bootstrapGeneratedFile{}, output.NewError("CLI_ERROR", "写入 agent skill wrapper 失败", map[string]any{
			"path":    path,
			"details": err.Error(),
		})
	}

	return bootstrapGeneratedFile{
		Kind: "agent-skill-native",
		Name: agent + " native skill wrapper",
		Path: path,
	}, nil
}

func buildAgentSkillWrapperLines() []string {
	lines := []string{
		"# PopiArt",
		"",
		"Use PopiArt when you need creator skill discovery, multimodal runtime skill execution, jobs, or artifacts.",
		"",
		"Preferred sequence:",
		"",
		"1. `popiart skills get <skill-id>`",
		"2. `popiart skills schema <skill-id>`",
		"3. `popiart run <skill-id> --input @params.json`",
		"4. `popiart jobs wait <job-id>`",
		"5. `popiart artifacts pull-all <job-id>`",
		"",
		"Official runtime baseline:",
		"",
	}
	for _, skill := range officialRuntimeSkills() {
		lines = append(lines, "- `"+skill.ID+"`: "+skill.Description)
	}
	lines = append(lines,
		"",
		"This file is generated by `popiart bootstrap` and can be placed directly in an agent-facing skill directory.",
		"",
		"MCP server entrypoint:",
		"",
		"`popiart mcp serve`",
		"",
	)
	return lines
}

func buildNativeMCPServerEntry(cfg config.Config) map[string]any {
	entry := map[string]any{
		"command": "popiart",
		"args":    []string{"mcp", "serve"},
	}
	if env := buildMCPEnvMap(cfg); len(env) > 0 {
		entry["env"] = env
	}
	return entry
}

func buildMCPEnvMap(cfg config.Config) map[string]string {
	env := map[string]string{
		"POPIART_CONFIG_DIR": config.Dir(),
		"POPIART_ENDPOINT":   cfg.Endpoint,
	}
	if cfg.Project != "" {
		env["POPIART_PROJECT"] = cfg.Project
	}
	return env
}

func upsertJSONMCPConfig(path string, cfg config.Config) error {
	root := map[string]any{}
	if data, err := os.ReadFile(path); err == nil && strings.TrimSpace(string(data)) != "" {
		if err := json.Unmarshal(data, &root); err != nil {
			return output.NewError("CLI_ERROR", "解析现有 agent MCP 配置失败", map[string]any{
				"path":    path,
				"details": err.Error(),
			})
		}
	} else if err != nil && !os.IsNotExist(err) {
		return output.NewError("CLI_ERROR", "读取现有 agent MCP 配置失败", map[string]any{
			"path":    path,
			"details": err.Error(),
		})
	}

	servers, ok := root["mcpServers"].(map[string]any)
	if !ok || servers == nil {
		servers = map[string]any{}
	}
	servers[popiartMCPServerID] = buildNativeMCPServerEntry(cfg)
	root["mcpServers"] = servers

	if err := writeJSONFile(path, root); err != nil {
		return output.NewError("CLI_ERROR", "写入 agent MCP 配置失败", map[string]any{
			"path":    path,
			"details": err.Error(),
		})
	}
	return nil
}

func upsertCodexMCPConfig(path string, cfg config.Config) error {
	existing := ""
	if data, err := os.ReadFile(path); err == nil {
		existing = string(data)
	} else if !os.IsNotExist(err) {
		return output.NewError("CLI_ERROR", "读取现有 Codex 配置失败", map[string]any{
			"path":    path,
			"details": err.Error(),
		})
	}

	updated := stripCodexMCPServerBlock(existing, popiartMCPServerID)
	updated = strings.TrimRight(updated, "\n")
	if updated != "" {
		updated += "\n\n"
	}
	updated += renderCodexMCPServerBlock(cfg) + "\n"

	if err := os.WriteFile(path, []byte(updated), 0o600); err != nil {
		return output.NewError("CLI_ERROR", "写入 Codex MCP 配置失败", map[string]any{
			"path":    path,
			"details": err.Error(),
		})
	}
	return nil
}

func stripCodexMCPServerBlock(doc, serverID string) string {
	lines := strings.Split(doc, "\n")
	prefix := "mcp_servers." + serverID
	out := make([]string, 0, len(lines))
	skipping := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			header := strings.TrimSpace(trimmed[1 : len(trimmed)-1])
			if header == prefix || strings.HasPrefix(header, prefix+".") {
				skipping = true
				continue
			}
			if skipping {
				skipping = false
			}
		}
		if skipping {
			continue
		}
		out = append(out, line)
	}

	for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "" {
		out = out[:len(out)-1]
	}
	return strings.Join(out, "\n")
}

func renderCodexMCPServerBlock(cfg config.Config) string {
	lines := []string{
		fmt.Sprintf("[mcp_servers.%s]", popiartMCPServerID),
		fmt.Sprintf("command = %s", tomlStringLiteral("popiart")),
		fmt.Sprintf("args = [%s, %s]", tomlStringLiteral("mcp"), tomlStringLiteral("serve")),
	}

	env := buildMCPEnvMap(cfg)
	if len(env) > 0 {
		lines = append(lines, "", fmt.Sprintf("[mcp_servers.%s.env]", popiartMCPServerID))
		keys := make([]string, 0, len(env))
		for key := range env {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			lines = append(lines, fmt.Sprintf("%s = %s", key, tomlStringLiteral(env[key])))
		}
	}

	return strings.Join(lines, "\n")
}

func tomlStringLiteral(value string) string {
	data, _ := json.Marshal(value)
	return string(data)
}
