package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/wtgoku-create/popiartcli/internal/output"
)

const (
	videoPromptEnhancerPollInterval = 2 * time.Second
	videoPromptEnhancerMaxPolls     = 300
)

func executeVideoGenerateCommand(cmd *cobra.Command, payload map[string]any, action string, preview map[string]any) error {
	enhancerModelID := strings.TrimSpace(flagString(cmd, "prompt-enhancer-model"))
	if enhancerModelID == "" {
		return executeSkillRun(cmd, officialImage2VideoSkillID, payload, action, preview)
	}

	enhancementInput, err := buildVideoPromptEnhancerInput(cmd, payload, preview)
	if err != nil {
		return err
	}

	videoPayload := cloneMapAny(payload)
	if videoPayload == nil {
		videoPayload = map[string]any{}
	}
	videoPayload["prompt"] = "(generated by prompt enhancer)"

	extras := map[string]any{
		"prompt_enhancement": map[string]any{
			"model_id": enhancerModelID,
		},
	}

	if dryRunMode(cmd) {
		videoRequestBody, err := buildVideoGenerateRequestBody(cmd, videoPayload)
		if err != nil {
			return err
		}
		return writeDryRunPreview(cmd, action, map[string]any{
			"execution_mode": "prompt-enhanced-image2video",
			"prompt_enhancement": map[string]any{
				"model_id": enhancerModelID,
				"request": map[string]any{
					"method": "POST",
					"path":   "/models/infer",
					"body":   buildModelInferBody(enhancerModelID, enhancementInput, flagString(cmd, "priority"), flagString(cmd, "idempotency-key")),
				},
			},
			"video_generation": videoRequestBody,
		})
	}

	enhancedPrompt, enhancementMeta, err := runVideoPromptEnhancement(context.Background(), cmd, enhancerModelID, enhancementInput)
	if err != nil {
		return err
	}

	videoPayload["prompt"] = enhancedPrompt
	extras["resolved_prompt"] = enhancedPrompt
	extras["prompt_enhancement"] = enhancementMeta
	return executeSkillRun(cmd, officialImage2VideoSkillID, videoPayload, action, mergeVideoExecutionPreview(preview, extras))
}

func buildVideoGenerateRequestBody(cmd *cobra.Command, payload map[string]any) (map[string]any, error) {
	modelOverride := strings.TrimSpace(flagString(cmd, "model"))
	if modelOverride != "" {
		directInput, err := normalizeOfficialRuntimeDirectInput(officialImage2VideoSkillID, payload)
		if err != nil {
			return nil, err
		}
		return map[string]any{
			"model_id":       modelOverride,
			"execution_mode": "direct-model-override",
			"request": map[string]any{
				"method": "POST",
				"path":   "/models/infer",
				"body":   buildModelInferBody(modelOverride, directInput, flagString(cmd, "priority"), flagString(cmd, "idempotency-key")),
			},
		}, nil
	}

	return map[string]any{
		"skill_id": officialImage2VideoSkillID,
		"request": map[string]any{
			"method": "POST",
			"path":   "/jobs",
			"body":   buildSkillJobBody(officialImage2VideoSkillID, payload, flagString(cmd, "priority"), flagString(cmd, "idempotency-key")),
		},
	}, nil
}

func buildVideoPromptEnhancerInput(cmd *cobra.Command, payload, preview map[string]any) (map[string]any, error) {
	input := map[string]any{
		"prompt": buildVideoPromptEnhancerInstruction(payload),
	}

	if sourceURL := stringValue(payload["image_url"]); sourceURL != "" {
		input["image_url"] = sourceURL
		input["reference_image_url"] = sourceURL
		return input, nil
	}

	sourceArtifactID := stringValue(payload["source_artifact_id"])
	if sourceArtifactID == "" {
		return nil, output.NewError("VALIDATION_ERROR", "提示词增强需要源图输入", map[string]any{
			"flag": "prompt-enhancer-model",
			"hint": "请传入 --image / --from 或 --source-artifact-id",
		})
	}

	uploadedSource, _ := preview["uploaded_source_artifact"].(map[string]any)
	if uploadedURL := stringValue(uploadedSource["url"]); uploadedURL != "" {
		input["image_url"] = uploadedURL
		input["reference_image_url"] = uploadedURL
	}
	input["source_artifact_id"] = sourceArtifactID
	return input, nil
}

func buildVideoPromptEnhancerInstruction(payload map[string]any) string {
	var sections []string
	sections = append(sections,
		"你是一名图生视频提示词设计助手。先理解输入图片的主体、场景、构图、镜头视角和可运动元素，再结合用户意图输出一个最终可直接用于 image-to-video 的提示词。",
		"只返回最终提示词本身，不要解释、不要 Markdown、不要 JSON、不要分点。",
		"默认保持原图主体身份、构图和关键视觉事实；只有当用户明确要求改变时才改动。",
		"在提示词中补全自然的主体动作、环境动态和镜头运动，但保持单镜头、短视频、可执行。",
	)

	appendPromptEnhancerField(&sections, "用户原始意图", stringValue(payload["prompt"]))
	appendPromptEnhancerField(&sections, "排除项", stringValue(payload["negative_prompt"]))
	appendPromptEnhancerField(&sections, "镜头运动", stringValue(payload["camera_motion"]))
	appendPromptEnhancerField(&sections, "运动强度", stringValue(payload["motion_intensity"]))
	appendPromptEnhancerField(&sections, "风格", stringValue(payload["style"]))
	appendPromptEnhancerField(&sections, "画幅比例", stringValue(payload["aspect_ratio"]))
	appendPromptEnhancerField(&sections, "补充说明", stringValue(payload["notes"]))
	if duration := numericValue(payload["duration_s"]); duration > 0 {
		sections = append(sections, fmt.Sprintf("目标时长：%.0f 秒", duration))
	}
	if len(sections) == 0 {
		return ""
	}
	return strings.Join(sections, "\n")
}

func appendPromptEnhancerField(dst *[]string, label, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	*dst = append(*dst, label+"："+value)
}

func runVideoPromptEnhancement(ctx context.Context, cmd *cobra.Command, modelID string, payload map[string]any) (string, map[string]any, error) {
	payload = hydratePromptEnhancerImageInput(ctx, payload)

	job, err := submitModelInferJob(ctx, modelID, payload, flagString(cmd, "priority"), "", flagString(cmd, "idempotency-key"))
	if err != nil {
		return "", nil, err
	}

	jobID := stringValue(job["job_id"])
	if jobID == "" {
		return "", nil, output.NewError("CLI_ERROR", "提示词增强响应缺少 job_id", map[string]any{
			"model_id": modelID,
		})
	}

	completedJob, err := waitForDynamicJob(ctx, jobID, videoPromptEnhancerPollInterval, videoPromptEnhancerMaxPolls)
	if err != nil {
		return "", nil, err
	}

	enhancedPrompt, err := extractTextFromJob(ctx, completedJob, "提示词增强结果")
	if err != nil {
		return "", nil, err
	}

	return enhancedPrompt, map[string]any{
		"model_id":        modelID,
		"job_id":          jobID,
		"execution_mode":  "direct-model-override",
		"enhanced_prompt": enhancedPrompt,
	}, nil
}

func hydratePromptEnhancerImageInput(ctx context.Context, payload map[string]any) map[string]any {
	input := cloneMapAny(payload)
	if input == nil {
		return map[string]any{}
	}
	if stringValue(input["image_url"]) != "" || stringValue(input["source_artifact_id"]) == "" {
		return input
	}

	var artifact map[string]any
	if err := currentClient().GetJSON(ctx, "/artifacts/"+stringValue(input["source_artifact_id"]), nil, &artifact); err != nil {
		return input
	}
	if artifactURL := stringValue(artifact["url"]); artifactURL != "" {
		input["image_url"] = artifactURL
		input["reference_image_url"] = artifactURL
	}
	return input
}

func waitForDynamicJob(ctx context.Context, jobID string, interval time.Duration, maxPolls int) (map[string]any, error) {
	for pollIndex := 0; pollIndex < maxPolls; pollIndex++ {
		var job map[string]any
		if err := currentClient().GetJSON(ctx, "/jobs/"+jobID, nil, &job); err != nil {
			return nil, err
		}

		status := strings.TrimSpace(stringValue(job["status"]))
		switch status {
		case "done", "cancelled":
			return job, nil
		case "failed":
			return nil, output.NewError("JOB_FAILED", dynamicJobMessage(job), map[string]any{
				"job_id": jobID,
				"status": status,
				"error":  job["error"],
			})
		}

		fmt.Fprintf(os.Stderr, "\r⏳ %s - %s (%ds)   ", jobID, status, int(interval.Seconds())*pollIndex)
		time.Sleep(interval)
	}

	return nil, output.NewError("POLL_TIMEOUT", fmt.Sprintf("Job %s did not complete within the timeout", jobID), map[string]any{
		"job_id":          jobID,
		"timeout_seconds": int(interval.Seconds()) * maxPolls,
	})
}

func dynamicJobMessage(job map[string]any) string {
	if errMap, ok := job["error"].(map[string]any); ok {
		if message := strings.TrimSpace(stringValue(errMap["message"])); message != "" {
			return message
		}
	}
	return "Job failed"
}

func extractTextFromJob(ctx context.Context, job map[string]any, sourceLabel string) (string, error) {
	if text := extractTextValue(job); text != "" {
		return text, nil
	}

	artifactIDs := extractStringSliceAny(job["artifact_ids"])
	for _, artifactID := range artifactIDs {
		text, ok, err := extractTextFromArtifact(ctx, artifactID)
		if err != nil {
			return "", err
		}
		if ok {
			return text, nil
		}
	}

	return "", output.NewError("TEXT_EXTRACTION_FAILED", "无法从"+strings.TrimSpace(sourceLabel)+"中提取文本结果", map[string]any{
		"job_id":       stringValue(job["job_id"]),
		"artifact_ids": artifactIDs,
	})
}

func extractTextFromArtifact(ctx context.Context, artifactID string) (string, bool, error) {
	var artifact map[string]any
	if err := currentClient().GetJSON(ctx, "/artifacts/"+artifactID, nil, &artifact); err != nil {
		return "", false, err
	}

	contentType := strings.ToLower(strings.TrimSpace(stringValue(artifact["content_type"])))
	filename := strings.ToLower(strings.TrimSpace(stringValue(artifact["filename"])))
	if !strings.Contains(contentType, "json") && !strings.Contains(contentType, "text") &&
		!strings.HasSuffix(filename, ".json") && !strings.HasSuffix(filename, ".txt") && !strings.HasSuffix(filename, ".md") {
		return "", false, nil
	}

	res, err := currentClient().Stream(ctx, "GET", "/artifacts/"+artifactID+"/content", apiOpts("", "application/octet-stream"))
	if err != nil {
		return "", false, err
	}
	defer res.Body.Close()

	body, err := io.ReadAll(res.Body)
	if err != nil {
		return "", false, output.NewError("NETWORK_ERROR", "读取文本工件失败", map[string]any{
			"artifact_id": artifactID,
			"details":     err.Error(),
		})
	}

	if text := extractTextValue(parseTextArtifactJSON(body)); text != "" {
		return text, true, nil
	}

	text := strings.TrimSpace(string(body))
	if text == "" {
		return "", false, nil
	}
	return text, true, nil
}

func parseTextArtifactJSON(body []byte) map[string]any {
	var payload map[string]any
	if err := json.Unmarshal(body, &payload); err != nil {
		return nil
	}
	return payload
}

func extractTextValue(value any) string {
	switch typed := value.(type) {
	case string:
		return strings.TrimSpace(typed)
	case map[string]any:
		for _, key := range []string{
			"enhanced_prompt",
			"resolved_prompt",
			"prompt",
			"output_text",
			"text",
			"response_text",
			"generated_text",
			"final_text",
			"content",
			"result",
			"output",
			"data",
		} {
			if nested := extractTextValue(typed[key]); nested != "" {
				return nested
			}
		}
	case []any:
		for _, item := range typed {
			if nested := extractTextValue(item); nested != "" {
				return nested
			}
		}
	}
	return ""
}

func extractStringSliceAny(value any) []string {
	switch typed := value.(type) {
	case []string:
		return append([]string(nil), typed...)
	case []any:
		items := make([]string, 0, len(typed))
		for _, item := range typed {
			if text := strings.TrimSpace(stringValue(item)); text != "" {
				items = append(items, text)
			}
		}
		return items
	default:
		return nil
	}
}

func mergeVideoExecutionPreview(preview, extras map[string]any) map[string]any {
	merged := cloneMapAny(preview)
	if merged == nil {
		merged = map[string]any{}
	}
	for key, value := range extras {
		merged[key] = value
	}
	return merged
}
