package cmd

import (
	"context"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/wtgoku-create/popiartcli/internal/output"
	"github.com/wtgoku-create/popiartcli/internal/popiart"
)

// executeVideoGenerateCommand 让普通图生视频和提示词增强都走主站链路。
func executeVideoGenerateCommand(cmd *cobra.Command, payload map[string]any, action string, preview map[string]any) error {
	enhancerModelID := strings.TrimSpace(flagString(cmd, "prompt-enhancer-model"))
	if enhancerModelID == "" {
		return executeTaskCommand(cmd, action, payload, popiart.BuildVideoGenerateTaskRequest, preview)
	}

	enhancementInput, err := buildVideoPromptEnhancerInput(cmd, payload, preview)
	if err != nil {
		return err
	}

	videoPayload := cloneMapAny(payload)
	if videoPayload == nil {
		videoPayload = map[string]any{}
	}
	videoPayload["prompt"] = "(generated by prompt enhancer)"

	extras := map[string]any{
		"prompt_enhancement": map[string]any{
			"model_id": enhancerModelID,
		},
	}

	if dryRunMode(cmd) {
		videoRequestBody, err := buildVideoGenerateRequestBody(cmd, videoPayload)
		if err != nil {
			return err
		}
		return writeDryRunPreview(cmd, action, map[string]any{
			"execution_mode": "prompt-enhanced-image2video",
			"prompt_enhancement": map[string]any{
				"model_id": enhancerModelID,
				"request": map[string]any{
					"method": "POST",
					"path":   "/api_client/anime/task/llmChat",
					"body":   buildVideoPromptEnhancerChatRequest(enhancerModelID, enhancementInput),
				},
			},
			"video_generation": videoRequestBody,
		})
	}

	enhancedPrompt, enhancementMeta, err := runVideoPromptEnhancement(context.Background(), cmd, enhancerModelID, enhancementInput)
	if err != nil {
		return err
	}

	videoPayload["prompt"] = enhancedPrompt
	extras["resolved_prompt"] = enhancedPrompt
	extras["prompt_enhancement"] = enhancementMeta
	return executeTaskCommand(cmd, action, videoPayload, popiart.BuildVideoGenerateTaskRequest, mergeVideoExecutionPreview(preview, extras))
}

// buildVideoGenerateRequestBody 为提示词增强 dry-run 生成第二段视频任务请求预览。
func buildVideoGenerateRequestBody(cmd *cobra.Command, payload map[string]any) (map[string]any, error) {
	modelOverride := strings.TrimSpace(flagString(cmd, "model"))
	model, err := popiart.ResolveModelForCommand(context.Background(), currentClient(), "video.generate", modelOverride, taskValidationSpecForAction("video.generate", payload))
	if err != nil {
		return nil, err
	}
	return map[string]any{
		"model_id":       model.Code,
		"execution_mode": taskExecutionMode(modelOverride),
		"request": map[string]any{
			"method": "POST",
			"path":   "/api_client/anime/task/create",
			"body":   popiart.BuildVideoGenerateTaskRequest(payload, model),
		},
	}, nil
}

func buildVideoPromptEnhancerInput(cmd *cobra.Command, payload, preview map[string]any) (map[string]any, error) {
	input := map[string]any{
		"prompt": buildVideoPromptEnhancerInstruction(payload),
	}

	if images := stringSliceValue(payload["images"]); len(images) > 0 && strings.TrimSpace(images[0]) != "" {
		sourceURL := strings.TrimSpace(images[0])
		input["image_url"] = sourceURL
		input["reference_image_url"] = sourceURL
		return input, nil
	}
	if sourceURL := stringValue(payload["image_url"]); sourceURL != "" {
		input["image_url"] = sourceURL
		input["reference_image_url"] = sourceURL
		return input, nil
	}

	sourceArtifactID := stringValue(payload["source_artifact_id"])
	if sourceArtifactID == "" {
		return nil, output.NewError("VALIDATION_ERROR", "提示词增强需要源图输入", map[string]any{
			"flag": "prompt-enhancer-model",
			"hint": "请传入 --image / --from 或 --source-artifact-id",
		})
	}

	uploadedSource, _ := preview["uploaded_source_artifact"].(map[string]any)
	if uploadedURL := stringValue(uploadedSource["url"]); uploadedURL != "" {
		input["image_url"] = uploadedURL
		input["reference_image_url"] = uploadedURL
	}
	input["source_artifact_id"] = sourceArtifactID
	return input, nil
}

func buildVideoPromptEnhancerChatRequest(modelCode string, input map[string]any) popiart.LLMChatRequest {
	request := popiart.LLMChatRequest{
		Model:  strings.TrimSpace(modelCode),
		Stream: false,
		Messages: []popiart.LLMChatMessage{
			{
				Role: "system",
				Content: []popiart.LLMChatContentPart{
					{
						Type: "text",
						Text: "你是一个提示词增强助手，优化用户输入的prompt，只输出增强后的prompt，不要输出额外的任何东西",
					},
				},
			},
		},
	}
	if aiModelID, ok := input["ai_model_id"].(int64); ok && aiModelID > 0 {
		request.AIModelID = aiModelID
	}
	userContent := []popiart.LLMChatContentPart{
		{
			Type: "text",
			Text: stringValue(input["prompt"]),
		},
	}
	if imageURL := strings.TrimSpace(firstNonEmptyString(stringValue(input["image_url"]), stringValue(input["reference_image_url"]))); imageURL != "" {
		userContent = append(userContent, popiart.LLMChatContentPart{
			Type:     "image_url",
			ImageURL: imageURL,
		})
	}
	request.Messages = append(request.Messages, popiart.LLMChatMessage{
		Role:    "user",
		Content: userContent,
	})
	return request
}

func buildVideoPromptEnhancerInstruction(payload map[string]any) string {
	var sections []string
	sections = append(sections,
		"你是一名图生视频提示词设计助手。先理解输入图片的主体、场景、构图、镜头视角和可运动元素，再结合用户意图输出一个最终可直接用于 image-to-video 的提示词。",
		"只返回最终提示词本身，不要解释、不要 Markdown、不要 JSON、不要分点。",
		"默认保持原图主体身份、构图和关键视觉事实；只有当用户明确要求改变时才改动。",
		"在提示词中补全自然的主体动作、环境动态和镜头运动，但保持单镜头、短视频、可执行。",
	)

	appendPromptEnhancerField(&sections, "用户原始意图", stringValue(payload["prompt"]))
	appendPromptEnhancerField(&sections, "排除项", stringValue(payload["negative_prompt"]))
	appendPromptEnhancerField(&sections, "镜头运动", stringValue(payload["camera_motion"]))
	appendPromptEnhancerField(&sections, "运动强度", stringValue(payload["motion_intensity"]))
	appendPromptEnhancerField(&sections, "风格", stringValue(payload["style"]))
	appendPromptEnhancerField(&sections, "画幅比例", stringValue(payload["aspect_ratio"]))
	appendPromptEnhancerField(&sections, "补充说明", stringValue(payload["notes"]))
	if duration := numericValue(payload["duration_s"]); duration > 0 {
		sections = append(sections, fmt.Sprintf("目标时长：%.0f 秒", duration))
	}
	if len(sections) == 0 {
		return ""
	}
	return strings.Join(sections, "\n")
}

func appendPromptEnhancerField(dst *[]string, label, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	*dst = append(*dst, label+"："+value)
}

func runVideoPromptEnhancement(ctx context.Context, cmd *cobra.Command, modelID string, payload map[string]any) (string, map[string]any, error) {
	payload = hydratePromptEnhancerImageInput(ctx, payload)
	model, err := popiart.ResolveModelForCommand(ctx, currentClient(), "image.describe", modelID, popiart.ModelValidationSpec{
		SubType:        501,
		RequiresImages: stringValue(payload["image_url"]) != "",
		ImageCount:     promptEnhancerImageCount(payload),
		VideoCount:     0,
		AudioCount:     0,
	})
	if err != nil {
		return "", nil, err
	}
	resp, err := popiart.EnhancePromptWithLLM(ctx, currentClient(), buildVideoPromptEnhancerChatRequest(model.Code, payloadWithResolvedModelID(payload, model.ID)))
	if err != nil {
		return "", nil, err
	}
	enhancedPrompt := ""
	if len(resp.Choices) > 0 {
		enhancedPrompt = strings.TrimSpace(resp.Choices[0].Message.Content)
	}
	if enhancedPrompt == "" {
		return "", nil, output.NewError("TEXT_EXTRACTION_FAILED", "无法从主站 llmChat 响应中提取增强后的 prompt", map[string]any{
			"model_id": model.Code,
			"hint":     "预期读取 data.choices[0].message.content",
		})
	}

	return enhancedPrompt, map[string]any{
		"model_id":        model.Code,
		"ai_model_id":     model.ID,
		"execution_mode":  "main-site-llm-chat",
		"enhanced_prompt": enhancedPrompt,
	}, nil
}

func payloadWithResolvedModelID(payload map[string]any, modelID int64) map[string]any {
	out := cloneMapAny(payload)
	if out == nil {
		out = map[string]any{}
	}
	out["ai_model_id"] = modelID
	return out
}

func hydratePromptEnhancerImageInput(ctx context.Context, payload map[string]any) map[string]any {
	input := cloneMapAny(payload)
	if input == nil {
		return map[string]any{}
	}
	if stringValue(input["image_url"]) != "" || stringValue(input["source_artifact_id"]) == "" {
		return input
	}

	var media map[string]any
	if err := currentClient().GetJSON(ctx, "/api_client/media/detail", map[string]string{"id": stringValue(input["source_artifact_id"])}, &media); err != nil {
		return input
	}
	if mediaURL := stringValue(media["url"]); mediaURL != "" {
		input["image_url"] = mediaURL
		input["reference_image_url"] = mediaURL
	}
	return input
}

func extractTextValue(value any) string {
	switch typed := value.(type) {
	case string:
		return strings.TrimSpace(typed)
	case map[string]any:
		for _, key := range []string{
			"enhanced_prompt",
			"resolved_prompt",
			"prompt",
			"output_text",
			"text",
			"response_text",
			"generated_text",
			"final_text",
			"content",
			"result",
			"output",
			"data",
		} {
			if nested := extractTextValue(typed[key]); nested != "" {
				return nested
			}
		}
	case []any:
		for _, item := range typed {
			if nested := extractTextValue(item); nested != "" {
				return nested
			}
		}
	}
	return ""
}

func promptEnhancerImageCount(payload map[string]any) int {
	if strings.TrimSpace(stringValue(payload["image_url"])) != "" || strings.TrimSpace(stringValue(payload["reference_image_url"])) != "" {
		return 1
	}
	return 0
}

func mergeVideoExecutionPreview(preview, extras map[string]any) map[string]any {
	merged := cloneMapAny(preview)
	if merged == nil {
		merged = map[string]any{}
	}
	for key, value := range extras {
		merged[key] = value
	}
	return merged
}
